[package]
name = "rust-xgboost-bindgen"
version = "0.1.0"
edition = "2021"
links = "xgboost"

[lib]
doctest = false

[dependencies]
libc = "0.2"

[dev-dependencies]
csv = "1.3"

[build-dependencies]
bindgen = "0.71"
cmake = "0.1"
